blank_issues_enabled: false
contact_links:
  - name: Project Manager Weekly Report
    url: https://github.com/your-repo/your-project/issues/new?template=project_manager_weekly_report.md
    about: Use this template to submit a weekly report as a project manager.